# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile for adb-mcp MCP server

# Use Node.js LTS on Alpine
FROM node:lts-alpine

# Install ADB (Android Debug Bridge)
RUN apk add --no-cache android-tools

# Set working directory
WORKDIR /app

# Copy package manifests
COPY package.json package-lock.json ./

# Install dependencies (skip prepare scripts if needed)
RUN npm ci --ignore-scripts

# Copy source code
COPY tsconfig.json ./
COPY src ./src

# Build TypeScript
RUN npm run build

# Expose no ports (stdio-based)

# Default entrypoint
ENTRYPOINT ["node", "dist/index.js"]
